import{_ as e,$ as a,a0 as n,a3 as s}from"./framework-24d1f903.js";const i={},d=s(`<h2 id="问题" tabindex="-1"><a class="header-anchor" href="#问题" aria-hidden="true">#</a> 问题</h2><p>比如现在有一台公网服务器，公网ip是111.111.111.111，内网ip是：10.1.1.1 。在这台服务器上面跑了两个服务：</p><ol><li><p>mysql</p><p>非docker方式，暴露的端口是3306，绑定的ip是0.0.0.0</p></li><li><p>nacos</p><p>docker方式，映射到宿主机的端口有8848和9848。连接的mysql地址是：111.111.111.111:3306/nacos</p></li></ol><p>现在发现的问题有：</p><ol><li>nacos总起不来，总提示<code>No DataSource set</code> ，但在本地却能连接 111.111.111.111:3306/nacos，并能读写数据</li><li>后面把nacos的mysql连接地址改10.1.1.1:3306/nacos后，nacos能启动成功了，但外网访问不了nacos的控制台</li></ol><p>这台服务器之前两个服务都能正常在公网访问，突然有一天发现不行了</p><p>查看防火墙端口设置：</p><figure><img src="https://cdn.justdopay.com/notion/md5-500b800b6d84bf28a0a3c1adc4b156aa.png" alt="Untitled" tabindex="0" loading="lazy"><figcaption>Untitled</figcaption></figure><p>8848端口也开了的，在服务器上执行<code>telnet 127.0.0.1 8848</code>也是通的，但执行<code>telnet 111.111.111.111 8848</code>就不通</p><p>网上各种乱搜，发现了始作俑者：<strong>ip_forward</strong></p><h2 id="解决过程" tabindex="-1"><a class="header-anchor" href="#解决过程" aria-hidden="true">#</a> 解决过程</h2><p>通过是否开启了路由转发 cat /proc/sys/net/ipv4/ip_forward</p><div class="language-json line-numbers-mode" data-ext="json"><pre class="language-json"><code>输出<span class="token number">0</span>表示没有开启，<span class="token number">1</span>表示开启了。此时输出的是<span class="token number">0</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>为0，表示禁用了路由转发，也就是说禁止了本机网卡之间的通信。</p><p>禁用后，在docker容器内部也就无法访问公网</p><p>也就是解释了为什么nacos的mysql地址设置为111.111.111.111:3306/nacos的时候启动不了</p><p>设置为1</p><div class="language-json line-numbers-mode" data-ext="json"><pre class="language-json"><code>不能直接vim /proc/sys/net/ipv4/ip_forward 来修改.

正确姿势：
vim /etc/sysctl.conf

找到net.ipv4.ip_forward，将其值修改为<span class="token number">1</span>. 或者在文末追加这个配置

net.ipv4.ip_forward = <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使其生效</p><div class="language-json line-numbers-mode" data-ext="json"><pre class="language-json"><code>sysctl -p
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>到此可以验证下在docker容器内部能否访问外网，我这里是重启了docker</p><p>至此，上面的服务都能正常访问了</p><h2 id="溯源" tabindex="-1"><a class="header-anchor" href="#溯源" aria-hidden="true">#</a> 溯源</h2><p>之前这两个服务一直都是好的，为啥“突然”就不行了。</p><p>回忆下来估计是中途按照了BBR，并重启了一次服务器，基本可以确定和这个有关系。</p><p><br><br><br><br><br><br></p><hr><hr><ul><li><strong>随机毒鸡汤</strong>：喜欢就像乘法一样，只要一方为零，结果便为零。 <br><br><img src="https://tuapi.eees.cc/api.php?category=dongman&amp;type=302&amp;uuid=06a9a9a5-6f4d-4d84-9963-acd8d138696e" alt="" loading="lazy"></li></ul>`,29),r=[d];function c(o,l){return a(),n("div",null,r)}const t=e(i,[["render",c],["__file","Docker隐射的端口外网不能访问.html.vue"]]);export{t as default};
